# -*- coding: utf-8 -*-
"""Pract1(DAA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dg_ccELC4bOf1ZDtkKJPXIzGHQzTpx-S
"""

# Insertion Sort
import time
n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

start = time.time()

# Insertion Sort
for i in range(1, n):
    key = arr[i]
    j = i - 1

    while j >= 0 and arr[j] > key:
        arr[j + 1] = arr[j]
        j -= 1

    arr[j + 1] = key

end = time.time()

print("Sorted array:", arr)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity:")
print("Best Case: O(n)")
print("Average Case: O(n²)")
print("Worst Case: O(n²)")
print("Space Complexity: O(1)")

# Bubble Sort - Simple Version
import time
n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

start = time.time()

# Bubble Sort
for i in range(n):
    for j in range(0, n - i - 1):
        if arr[j] > arr[j + 1]:
            arr[j], arr[j + 1] = arr[j + 1], arr[j]

end = time.time()

print("Sorted array:", arr)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity:")
print("Best Case: O(n²)")
print("Average Case: O(n²)")
print("Worst Case: O(n²)")
print("Space Complexity: O(1)")

# Selection Sort
import time
n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

start = time.time()

# Selection Sort
for i in range(n):
    min_index = i

    for j in range(i + 1, n):
        if arr[j] < arr[min_index]:
            min_index = j

    arr[i], arr[min_index] = arr[min_index], arr[i]

end = time.time()

print("Sorted array:", arr)
print("Execution Time:", end - start, "seconds")

print("\nTime Complexity:")
print("Best Case: O(n²)")
print("Average Case: O(n²)")
print("Worst Case: O(n²)")
print("Space Complexity: O(1)")

import time

# Quick Sort
def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    pivot = arr[0]

    left = []
    right = []

    for i in arr[1:]:
        if i <= pivot:
            left.append(i)
        else:
            right.append(i)

    return quick_sort(left) + [pivot] + quick_sort(right)

n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

# Start execution time
start_time = time.perf_counter()

arr = quick_sort(arr)

# End execution time
end_time = time.perf_counter()

execution_time = end_time - start_time

print("Sorted array:", arr)

print("\nExecution Time: {:.8f} seconds".format(execution_time))

print("\nTime Complexity:")
print("Best Case: O(n log n)")
print("Average Case: O(n log n)")
print("Worst Case: O(n²)")
print("Space Complexity: O(n)")

import time

# Merge Sort
def merge_sort(arr):
    if len(arr) > 1:

        mid = len(arr) // 2

        left = arr[:mid]
        right = arr[mid:]

        merge_sort(left)
        merge_sort(right)

        i = j = k = 0

        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                arr[k] = left[i]
                i += 1
            else:
                arr[k] = right[j]
                j += 1
            k += 1

        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1

n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

# Start execution time
start_time = time.perf_counter()

merge_sort(arr)

# End execution time
end_time = time.perf_counter()

print("Sorted array:", arr)

print("\nExecution Time: {:.8f} seconds".format(end_time - start_time))

print("\nTime Complexity:")
print("Best Case: O(n log n)")
print("Average Case: O(n log n)")
print("Worst Case: O(n log n)")
print("Space Complexity: O(n)")

